### ISSUE TITLE
search script uncomplete？

### ISSUE THREAD

**Issue by rubyrosecraft** [xiaoiker/GCN-NAS#12]
Thanks for your job! But it seems that gcn_search.py script is uncomplete for I found several Unresolved references 'xxxx' in the following part :

 # refrence
    for i in range(opt.begin_epoch, opt.n_epochs + 1):
        es_params, n_reused, idx_reused = sampler.ask(pop_size, old_es_params)
        print('es shape {}'.format(es_params.shape))
 
        if i > 0:
            sample = es.ask(1).reshape(-1)
            es_param = sample.reshape(n_connections,-1)
            NAS_model.alphas_normal = torch.from_numpy(es_param).float().cuda()
              
        logging.info('epoch %d lr %e', i, lr)
        genotype = NAS_model.genotype()
        logging.info('genotype = %s', genotype)
        
        if not opt.no_train:
            train_acc, train_losses = ces_search(i, train_loader, NAS_model, criterion, optimizer, opt, train_logger, train_batch_logger)
            logging.info('train_acc %f', train_acc)
        if not opt.no_val:
            with torch.no_grad():
                num_valid = i
                if num_valid > pop_size:
                    num_valid = pop_size
                for j in range(num_valid):
                    es_param = es_params[j]
                    print(es_param.shape)
                    es_param = es_param.reshape(n_connections,-1)
                    NAS_model.alphas_normal = torch.from_numpy(es_param).float().cuda()

                    scores[j] = val_epoch(i, val_loader, NAS_model, criterion, opt, val_logger)
                    #scores.append(score)
                    
                    genotype = NAS_model.genotype()
                    logging.info('genotype = %s', genotype)
                    
                    logging.info('valid_acc %f', scores[j])
                
        
        es.tell(es_params, scores)
        old_es_params = deepcopy(es_params)
        #old_scores = deepcopy(scores)
**Can you solve my question? Please guide me if a search script is shared.**
Thanks!

**Comment by rubyrosecraft** [comment]
I didn't find some scripts that contain 'genotype ', 'NAS_model' and etc. It confuses me a lot.

**Comment by xiaoiker** [comment]
Oh, I am sorry for that, I forgot to remove this. You can directly run the main function here. The search part do not need this part. I also remove it here.

**Comment by rubyrosecraft** [comment]
Thanks for your reply.
