### ISSUE TITLE
models about GCN-NAS

### ISSUE THREAD

**Issue by melon-coder** [xiaoiker/GCN-NAS#16]
Hello
    I saw your article about GCN-NAS, thank you for your article, this article inspired me something.  But I found that you did not make the trained model public, so I would like to ask you to send me the model trained on the relevant data set, okay? If you see this information, I hope you can take time to reply to me, thank you very much!
    My email address: renbowei333@163.com

**Comment by xiaoiker** [comment]
Sent.

**Comment by Lyndsey-Xing** [comment]
> Sent.

Hi, this paper of yours is very thoughtful and has inspired me a lot. Now I need your models to supplement the experimental data, so I am in great need of your models of NTU 60 CSub and NTU 120 CSet, and would like to receive the full models of NTU 60 and NTU 120 if it is convenient. My email is: yulingxing@m.scnu.edu.cn.

I hope to hear from you soon, and thanks again!

**Comment by xiaoiker** [comment]
> 

sent

**Comment by abhigoku10** [comment]
@xiaoiker thanks a lot for opensourcing the code base , can you please share the trained model to the following mail id abhigoku10@gmail.com
