### ISSUE TITLE
Questions on data generation

### ISSUE THREAD

**Issue by b224618** [xiaoiker/GCN-NAS#2]
Hi,

The ntu_gendata.py file only generates data for xset but doesnt generate data for xsub or xview. But the configs are set for xsub and xview, and thus I fail to run the code. Could you please provide some instructions on this problem?

Thank you so much!

**Comment by Anirudh257** [comment]
You have to change the line 155 to 

> benchmark = ['xsub', 'xset']

**Comment by b224618** [comment]
> You have to change the line 155 to
> 
> > benchmark = ['xsub', 'xset']

Thanks!

**Comment by Anirudh257** [comment]
No problem :)
