### ISSUE TITLE
gendata error

### ISSUE THREAD

**Issue by XiongXintyw** [xiaoiker/GCN-NAS#3]
When I run "python data_gen/ntu_gendata.py", gets the error : ModuleNotFoundError: No module named 'data_gen'.

When I run "python data_gen/kinetics_gendata.py", gets the error : FileNotFoundError: [Errno 2] No such file or directory: '../data/kinetics_raw/kinetics_val'.

My raw data has put in the ./data.

Needs your help！

**Comment by xiaoiker** [comment]
Try modify '../data/kinetics_raw/kinetics_val' to './data/kinetics_raw/kinetics_val', or get into the subfolder data_gen/ by cd data_gen, and then run python ntu_gendata.py. Hope it helps.  Feel free to open this issue again if needed.
