### ISSUE TITLE
python data_gen/kinetics-gendata.py issue

### ISSUE THREAD

**Issue by JoshaPan** [xiaoiker/GCN-NAS#4]
when I type the command: python data_gen/kinetics-gendata.py
the code needs the 'python data_gen/kinetics-gendata.py' file

Can you tell me where is the jason file?
thanks

**Comment by XiongXintyw** [comment]
Use the code : python data_gen/kinetics_gendata.py

> when I type the command: python data_gen/kinetics-gendata.py
> the code needs the 'python data_gen/kinetics-gendata.py' file
> 
> Can you tell me where is the jason file?
> thanks

Use the code : python data_gen/kinetics_gendata.py
