### ISSUE TITLE
ImportError: cannot import name 'agcn2'

### ISSUE THREAD

**Issue by XiongXintyw** [xiaoiker/GCN-NAS#5]
Hi, thank you for the code.

When the order :    python main.py --config ./config/nturgbd-cross-view/train_joint.yaml
                               python main.py --config ./config/nturgbd-cross-view/train_bone yaml
                               python main.py --config ./config/nturgbd-cross-subject/train_joint.yaml
                               python main.py --config ./config/nturgbd-cross-subject/train_bone.yaml

All got the error :    ImportError: cannot import name 'agcn2'

Please give me instructions,thanks!

**Comment by dongle329** [comment]
I also have this problem

**Comment by xiaoiker** [comment]
Hey, 
This Bug can simply sovled by remove the line 2 of __init__.py in model/ 
I also remove it here. Thanks. And also take care of the configuration files, we train with the agcn3.model

All the best
